version: 2.1

jobs:
  build_and_push:
    docker:
      - image: docker:19.03.8-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t social_media_frontend:$version .
            docker tag social_media_frontend:$version satyam19arya/social_media_frontend:$version
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push satyam19arya/social_media_frontend:$version

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/satyam19arya/social_media_yaml_manifest.git
            git config --global user.email "satyam19arya@gmail.com"
            git config --global user.name "satyam19arya"
            cd social_media_yaml_manifest
            sed -i "s/build-.*/build-$TAG/g" manifest/front_deployment.yaml
            git add .
            git commit -m "updated image version:$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/satyam19arya/social_media_yaml_manifest.git master 

workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - Update_manifest:
          requires:
            - build_and_push